#!/usr/bin/env python3
''' Async generator that takes no arguments'''

import asyncio
import random uniform
from typing import Generator


async def async_generator() -> Generator[float, None, None]:
    ''' An async that generates a float number'''

    for _ in range(10):
        await asyncio.sleep(1)
        yield random.random() * 10
